version: '3.3'
services:
  pgpool:
    image: rueian/pgpool:3.7.5-debian9
    ports:
      - "5432:9999"
    volumes:
      - ./pgpool.conf:/etc/pgpool/pgpool.conf
      - ./pcp.conf:/etc/pgpool/pcp.conf
      - ./pool_hba.conf:/etc/pgpool/pool_hba.conf
  pg0:
    image: postgres:10-alpine
  pg1:
    image: postgres:10-alpine
